Download session & subject archives with new API
opencap-org/opencap-viewer pull request #127
Opened 2023-05-26 07:08 UTC by anastasiiadidan

2023-05-30 08:16 UTC, antoinefalisse requested changes
@anastasiiadidan, this is looking great. I left some minor comments. Thanks.

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Step5.vue
> +                                    Do you want to download all data associated to the
Rephrase: Do you want to download all the data from session <>

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Step5.vue
> +                                    (This includes every trial associated to it, and can take several minutes).
Rephrase: (This can take several minutes)

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Step5.vue
> +                                    The archive has been generated successfully!
Rephrase: The archive has been successfully generated. Click on data.zip to download.

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Step5.vue
> +                                {{archiveName}}
Could we just use data.zip for the button, the full archive name is complicated and there is no confusion possible so no need to incorporate the session ID in the button name.

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Subjects.vue
> +                                    The archive has been generated successfully!
Rephrase: The archive has been successfully generated. Click on data.zip to download.

2023-05-30 08:16 UTC, antoinefalisse commented on src/components/pages/Subjects.vue
> +                                    {{archiveName}}
Could we just use data.zip for the button, the full archive name is complicated (eg, users do not know about the index of a subject) and there is no confusion possible so no need to incorporate the user ID in the button name.

2023-05-30 08:53 UTC, olehkorkh-planeks approved these changes

2023-05-30 15:09 UTC, antoinefalisse approved these changes

2023-05-31 07:44 UTC, antoinefalisse approved these changes

2023-05-31 07:45 UTC, merged